#!/bin/bash

BASE=/opt/slx/bluepages/

username=$1

# check usage
if [[ -z "$username" ]]; then
	echo "Usage: $0 <username>"
	exit 1
fi

# check if this username already exists
id $username &>/dev/null
if [[ $? -ne 0 ]]; then
	echo "The account $username does not exist (or is not active)"
	exit 2
fi

if [[ $EUID -ne 0 ]]; then
    echo "This script must be ran as root"
    exit 3
fi  

# create the user account with all default values
$BASE/updatebp.py -s disabled -b $username

# export to ldap 
$BASE/exportbp.py

