#!/bin/bash

BASE=/opt/slx/bluepages/
OU="ou=people,dc=example,dc=com"

username=$1

# check usage
if [[ -z "$username" ]]; then
	echo "Usage: $0 <username>"
	exit 1
fi

# check if this username exists
id $username &>/dev/null
if [[ $? -ne 0 ]]; then
	echo "The account $username does not exist"
	exit 2
fi

if [[ $EUID -ne 0 ]]; then
    echo "This script must be ran as root"
    exit 3
fi  

pwfile=$(mktemp)
chmod 600 $pwfile
pwgen -1 16 > $pwfile

if [[ -x /usr/bin/ldappasswd ]]; then
	ldappasswd -w $(cat /etc/ldap.secret) -s $(cat $pwfile) -x -Z -D "CN=Directory Manager" uid=${username},${OU}
fi

# set samba password (if installed)
if [[ -x /usr/bin/smbpasswd ]]; then
	cat $pwfile $pwfile | smbpasswd  -s $username
fi


echo "The account $username has been set with password: $(cat $pwfile)"
echo "Please record this password as it can not be retrieved again"

rm $pwfile
